# Generated by Django 6.0.3 on 2026-03-23 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('student_class', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Students',
        ),
    ]
