# Generated by Django 6.0.3 on 2026-03-30 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0002_complaint_delete_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='student_class',
            field=models.CharField(max_length=50),
        ),
    ]
