# Generated by Django 6.0.3 on 2026-03-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaint', '0005_alter_complaint_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='department',
            field=models.CharField(default='unknown', max_length=100),
            preserve_default=False,
        ),
    ]
